Repository teamproject-LUTI/backend, pull requests merged in 2025-06, with the labels that each got.

#18 [FEAT] travel 레포 설계
  src/main/java/com/luti/travel/entity/TravelRecord.java
  src/main/java/com/luti/travel/repository/AccomoDetailRepository.java
  src/main/java/com/luti/travel/repository/AccomoInfoRepository.java
Labels: enhancement, refactor

#26 [FIX] 엔티티 복합키 참조 문제 해결
  src/main/java/com/luti/auth/entity/User.java
  src/main/java/com/luti/auth/entity/UserType.java
  src/main/java/com/luti/payment/antity/PaymentList.java
  src/main/java/com/luti/payment/antity/PaymentMethod.java
  src/main/java/com/luti/payment/antity/id/PaymentListId.java
  src/main/java/com/luti/payment/repository/PaymentListRepository.java
  src/main/java/com/luti/payment/repository/PaymentMethodRepository.java
  src/main/java/com/luti/travel/entity/AccomoDetail.java
  src/main/java/com/luti/travel/entity/AccomoInfo.java
  src/main/java/com/luti/travel/entity/TravelRecord.java
  src/main/java/com/luti/travel/repository/AccomoDetailRepository.java
  src/main/java/com/luti/travel/repository/AccomoInfoRepository.java
  src/main/java/com/luti/utils/UriCreator.java
Labels: bug

#37 공지
  src/main/java/com/luti/board/controller/NoticeAttachmentController.java
  src/main/java/com/luti/board/controller/NoticeController.java
  src/main/java/com/luti/board/dto/AskResponseDto.java
  src/main/java/com/luti/board/dto/NoticeAttachmentRequestDto.java
  src/main/java/com/luti/board/dto/NoticeAttachmentResponseDto.java
  src/main/java/com/luti/board/repository/NoticeAttachmentRepository.java
  src/main/java/com/luti/board/service/NoticeAttachmentService.java
Labels: enhancement

#61 문의,댓글 기능
  src/main/java/com/luti/board/controller/AskAttachmentController.java
  src/main/java/com/luti/board/controller/AskController.java
  src/main/java/com/luti/board/controller/CommentController.java
  src/main/java/com/luti/board/dto/AskAttachmentRequestDto.java
  src/main/java/com/luti/board/dto/AskAttachmentResponseDto.java
  src/main/java/com/luti/board/dto/AskRequestDto.java
  src/main/java/com/luti/board/entity/Notice.java
  src/main/java/com/luti/board/repository/AskAttachmentRepository.java
  src/main/java/com/luti/board/repository/AskRepository.java
  src/main/java/com/luti/board/service/AskAttachmentService.java
  src/main/java/com/luti/board/service/AskService.java
  src/main/java/com/luti/board/service/CommentService.java
Labels: enhancement

#69 [FIX] #68 paymentcd 타입 변경
  application.properties
  settings.gradle
  src/main/java/com/luti/payment/dto/PaymentListRequestDTO.java
  src/main/java/com/luti/payment/dto/PaymentListResponseDTO.java
  src/main/java/com/luti/payment/dto/PaymentMethodResponseDTO.java
  src/main/java/com/luti/payment/entity/PaymentList.java
  src/main/java/com/luti/payment/entity/PaymentMethod.java
  src/main/java/com/luti/payment/repository/PaymentMethodRepository.java
  src/main/java/com/luti/payment/service/PaymentMethodService.java
  src/main/java/com/luti/travel/entity/TravelRecord.java
Labels: enhancement

#82 Refactor/mypage
  src/main/java/com/luti/auth/controller/AuthController.java
  src/main/java/com/luti/auth/service/AuthService.java
  src/main/java/com/luti/config/SecurityConfig.java
  src/main/java/com/luti/config/WebConfig.java
  src/main/java/com/luti/mypage/controller/MyPageProfileController.java
  src/main/java/com/luti/mypage/controller/WithdrawController.java
  src/main/java/com/luti/mypage/dto/response/ProfileImageResponseDto.java
  src/main/java/com/luti/mypage/service/FileStorageService.java
  src/main/java/com/luti/mypage/service/MyPageService.java
  src/main/java/com/luti/mypage/service/ProfileImageService.java
Labels: enhancement

#86 토스트 에디터 적용
  .gitignore
  src/main/java/com/luti/board/controller/LikeController.java
  src/main/java/com/luti/board/controller/ReviewAttachmentController.java
  src/main/java/com/luti/board/controller/ReviewController.java
  src/main/java/com/luti/board/controller/ReviewImageUploadController.java
  src/main/java/com/luti/board/dto/LikeRequestDto.java
  src/main/java/com/luti/board/dto/LikeResponseDto.java
  src/main/java/com/luti/board/dto/LikedReviewDto.java
  src/main/java/com/luti/board/dto/ReviewAttachmentRequestDto.java
  src/main/java/com/luti/board/dto/ReviewAttachmentResponseDto.java
  src/main/java/com/luti/board/dto/ReviewResponseDto.java
  src/main/java/com/luti/board/entity/Review.java
  src/main/java/com/luti/board/entity/ReviewAttachment.java
  src/main/java/com/luti/board/repository/LikeRepository.java
  src/main/java/com/luti/board/repository/ReviewRepository.java
  src/main/java/com/luti/board/service/LikeService.java
  src/main/java/com/luti/board/service/ReviewAttachmentService.java
  src/main/java/com/luti/board/service/ReviewService.java
  src/main/java/com/luti/config/WebMvcConfig.java
  src/main/java/com/luti/travel/controller/NaverLocalSearchController.java
  src/main/java/com/luti/travel/service/NaverLocalSearchService.java
Labels: enhancement

#97 [FEAT] 비밀번호 수정
  src/main/java/com/luti/mypage/controller/PasswordController.java
  src/main/java/com/luti/mypage/dto/request/PasswordUpdateRequestDto.java
  src/main/java/com/luti/mypage/service/PasswordService.java
Labels: enhancement

#99 결제 페이지 필터 구현#98
  src/main/java/com/luti/payment/repository/PaymentListRepository.java
  src/main/java/com/luti/payment/service/PaymentListService.java
Labels: enhancement

#115 [FEAT] 내가 쓴 QnA 조회 구현
  src/main/java/com/luti/board/controller/AskController.java
  src/main/java/com/luti/board/repository/AskRepository.java
  src/main/java/com/luti/board/repository/MyAskSearchDto.java
  src/main/java/com/luti/board/service/AskService.java
  src/main/java/com/luti/mypage/controller/MyPageProfileController.java
  src/main/java/com/luti/mypage/dto/response/MyPageProfileResponseDto.java
  src/main/java/com/luti/mypage/service/MyPageService.java
Labels: enhancement

#117 리뷰 파일첨부 기능 추가
  src/main/java/com/luti/board/controller/ReviewAttachmentController.java
  src/main/java/com/luti/board/controller/ReviewController.java
  src/main/java/com/luti/board/controller/ReviewImageUploadController.java
  src/main/java/com/luti/board/repository/ReviewRepository.java
  src/main/java/com/luti/board/service/ReviewAttachmentService.java
  src/main/java/com/luti/board/service/ReviewService.java
Labels: enhancement

#120 backend: 첨부 기능
  src/main/java/com/luti/board/controller/AskAttachmentController.java
  src/main/java/com/luti/board/controller/AskController.java
  src/main/java/com/luti/board/controller/NoticeAttachmentController.java
  src/main/java/com/luti/board/entity/AskAttachment.java
  src/main/java/com/luti/board/entity/NoticeAttachment.java
  src/main/java/com/luti/board/entity/ReviewAttachment.java
  src/main/java/com/luti/board/service/AskAttachmentService.java
  src/main/java/com/luti/board/service/AskService.java
  src/main/java/com/luti/board/service/NoticeAttachmentService.java
Labels: enhancement

#124 [FEAT] payment 정보 수정 및 호텔 정보 저장#123
  src/main/java/com/luti/payment/controller/PaymentListController.java
  src/main/java/com/luti/payment/dto/PaymentWithReservationDTO.java
  src/main/java/com/luti/payment/service/PaymentListService.java
  src/main/java/com/luti/travel/dto/AccomodationDetailRequestDTO.java
  src/main/java/com/luti/travel/dto/TripPlanDto.java
  src/main/java/com/luti/travel/entity/AccomodationDetail.java
  src/main/java/com/luti/travel/repository/AccomodationDetailRepository.java
  src/main/java/com/luti/travel/service/AccomodationDetailService.java
Labels: enhancement

#126 [FEAT]숙소 예약하기 기능 구현 #125
  src/main/java/com/luti/travel/controller/HotelBookingController.java
  src/main/java/com/luti/travel/dto/HotelBookingDto.java
  src/main/java/com/luti/travel/entity/AccomodationDetail.java
  src/main/java/com/luti/travel/entity/AccomodationInformation.java
  src/main/java/com/luti/travel/repository/AccomoDetailRepository.java
  src/main/java/com/luti/travel/service/HotelBookingService.java
Labels: enhancement
